using namespace std;
	int WeaponCell1[][5] = {
    {0,0,0,0,0},
    {1, 1, 1, 1, 1},
	{2, 2, 2, 2, 2},
	{3, 3, 3, 3, 3},
	{1, 1, 1, 1, 1},
	{1, 1, 1, 1, 1},
	{2, 2, 2, 2, 2},
	{3, 3, 3, 3, 3},
	{5, 5, 5, 5, 5},
	{2, 2, 2, 2, 2},
	{4, 4, 4, 4, 4},
	{3, 3, 3, 3, 3},
	{1, 1, 1, 1, 1},
	{5, 5, 5, 5, 5},
	{1, 1, 1, 1, 1},
	{2, 2, 2, 2, 2},
	{5, 5, 5, 5, 5},
	{4, 4, 4, 4, 4},
	{4, 3, 4, 3, 4},
	{3, 3, 3, 3, 3},
	{4, 100, 100, 100, 100}};
        int WeaponCell2[][5] = {
        {0,0,0,0,0},
		{ 3, 3, 4, 3, 4 },
		{ 4, 3, 4, 3, 4 },
		{ 3, 3, 3, 3, 3 },
		{ 3, 3, 3, 3, 3 },
		{ 4, 3, 4, 3, 4 },
		{ 4, 3, 4, 3, 4 },
		{ 5, 1, 4, 1, 4 },
		{ 2, 3, 4, 3, 4 },
		{ 4, 3, 4, 3, 4 },
		{ 2, 3, 2, 3, 2 },
		{ 5, 5, 5, 5, 5 },
		{ 3, 3, 4, 3, 4 },
		{ 1, 5, 4, 3, 1 },
		{ 4, 3, 4, 3, 4 },
		{ 2, 3, 4, 3, 4 },
		{ 4, 3, 3, 3, 4 },
		{ 5, 5, 5, 5, 5 },
		{ 5, 2, 3, 2, 3 },
		{ 5, 5, 5, 5, 5 },
		{2, 100, 100, 100, 100}};
			string CellList[] = { "None", "Assassin's Vigour", "Bloodless", "Fireproof", "Fortress", "Guardian", "Iceborne", "Insulated", "Nine Lives", "Shellshock Resist", "Sturdy", "Tough", "Warmth", "Agility", "Conditioning", "Endurance", "Evasion", "Fleet Footed", "Nimble", "Swift", "Aetherhunter", "Deconstruction", "Knockout King", "Overpower", "Pacifier", "Rage", "Ragehunter", "Sharpened", "Acidic", "Adrenaline", "Barbed", "Bladestorm", "Cunning", "Evasive Fury", "Merciless", "Molten", "Predator", "Savagery", "Weighted Strikes", "Wild Frenzy", "Aetherborne", "Aetheric Attunement", "Aetheric Frenzy", "Conduit", "Energized", "Lucent", "Medic", "Stunning Vigour", "Vampiric"};
	string  DefenceCellList[] = { "Assassins Vigour", "Bloodless", "Fireproof", "Fortress", "Guardian", "Iceborne", "Insulated", "Nine Lives", "Shellshock Resist", "Sturdy", "Tough", "Warmth"};
	string  MobilityCellList[] = { "Agility", "Conditioning", "Endurance", "Evasion", "Fleet Footed", "Nimble", "Swift"};
	string  PowerCellList[] = { "Aetherhunter", "Deconstruction", "Knockout King", "Overpower", "Pacifier", "Rage", "Ragehunter", "Sharpened"};
	string  TechniqueCellList[] = { "Acidic", "Adrenaline", "Barbed", "Bladestorm", "Cunning", "Evasive Fury", "Merciless", "Molten", "Predator", "Savagery", "Weighted Strikes", "Wild Frenzy"};
	string  UtilityCellList[] = { "Aetherborne", "Aetheric Attunement", "Aetheric Frenzy", "Conduit", "Energized", "Lucent", "Medic", "Stunning Vigour", "Vampiric"};
	string CellTypeList[] = { "None", "Defense", "Mobility", "Power", "Technique", "Utility" };
	string WeaponType[] = { "Sword", "Hammer", "ChainBlades", "Axe", "WarPike" };
	string ArmorTypeList[] = { "Head", "Torso", "Arms", "Legs" };
	string ID[] = {"Recruit's","Charrogg","Embermane","Hellion","Boreus","Pangar","Skraev","Drask","Nayzaga","Stormclaw","Kharabak","Koshai","Skarn","Gnasher","Quillshot","Shrike","Shrowd","Riftstalker","Rezakiri","Valomyr","Charrogg Exotic","Shroud Exotic","Rezakiri Exotic" };
	string WeaponName[][5] = {
        { "Recruit's Sword", "Recruit's Hammer", "Recruit's Chain Blades", "Recruit's Axe", "Recruit's War Pike"},
		{ "Charred Saber", "Charred Crusher ", "Charred Blades", "Charred Cleaver", "Charred Spear" },
		{ "Ember Cutlass", "Ember Maul", "Ember Blades", "Ember Sycthe", "Ember Pike" },
		{ "Inferno's Razor", "Inferno's Burden", "Inferno's Fangs", "Inferno's Decree", "Inferno's Arrow" },
		{ "Onus of Boreus", "Brutality of Boreus", "Destiny of Boreus", "Turmoil of Boreus", "Revolution of Boreus" },
		{ "Pangar's Call", "Pangar's Rampage", "Pangar's Claws", "Pangar's Grace", "Pangar's Tooth" },
		{ "Winter Ice", "Winter Squall", "Winter Winds", "Winter Gale", "Winter Vortex" },
		{ "Thundering Blade", "Thundering Maul", "Thundering Cutters", "Thundering Scythe", "Thundering Spear" },
		{ "Nayzaga's Razor", "Nayzaga's Charge", "Nayzaga's Reach", "Nayzaga's Charge", "Nayzaga's Fang" },
		{ "Storm Sword", "Storm Hammer", "Storm Blades", "Storm Cutter", "Storm Pike" },
		{ "Kharabak's Spur", "Kharabak's Jaw", "Kharabak's Wings", "Kharabak's Claw", "Kharabak's Sting" },
		{ "Sovreign's Torment", "Sovreign's Grudge", "Sovreign's Lash", "Sovreign's Wrath", "Sovreign's Sorrow" },
		{ "Rockfall's Rancor", "Rockfall's Wrath", "Rockfall's Malice", "Rockfall's Judgement", "Rockfall's Spite" },
		{ "Raging Blade", "Raging Crash", "Raging Teeth", "Raging Bite", "Raging Cruelty" },
		{ "Quillshot's Tusk", "Quillshot's Roar", "Quillshot's Bonehooks", "Quillshot's Fury", "Quillshot's Javelin" },
		{ "Cry of the Shrike", "Fall of the Shrike", "Flight of the Shrike", "Song of the Shrike", "Scream of the Shrike" },
		{ "Eyes of Night", "Fall of Night", "Verge of Night", "Reaper of Night", "Gyre of Night" },
		{ "Stalker's Strike", "Stalker's Price", "Stalker's Trap", "Stalker's Mercy", "Stalker's Spike" },
		{ "Call of Dawn", "Break of Dawn", "Fangs of Dawn", "Edge of Dawn", "Spire of Dawn" },
		{ "Valomyr's Regard", "Valomyr's Burden", "Valomyr's Revenge", "Valomyr's Decree", "Valomyr's Hope" },
		{"Repeaters", "error", "error", "error", "error"}
	};
	int WeaponPerk[][5] = {
        {0,0,0,0,0},
		{ 20, 20, 20, 20, 20 },
		{ 33, 33, 33, 33, 33 },
		{ 23, 23, 23, 23, 23 },
		{ 14, 14, 14, 14, 14 },
		{ 22, 22, 38, 22, 38 },
		{ 18, 18, 18, 18, 18 },
		{ 41, 41, 41, 41, 41 },
		{ 30, 37, 30, 37, 30 },
		{ 44, 41, 44, 44, 44 },
		{ 31, 21, 31, 21, 31 },
		{ 27, 27, 27, 27, 27 },
		{ 22, 22, 38, 22, 38 },
		{ 26, 26, 26, 26, 26 },
		{ 28, 28, 28, 28, 28 },
		{ 14, 14, 14, 14, 14 },
		{ 32, 32, 32, 32, 32 },
		{ 39, 39, 39, 39, 39 },
		{ 32, 32, 32, 32, 32 },
		{ 20, 20, 20, 20, 20 },
		{ 0, 100, 100, 100, 100}};
	string ArmorName[][4]{
		{ "Recruit's Mask", "Recruit's Breastplate", "Recruit's Gloves", "Recruit's Greaves" },
		{ "Volcanic Helm", "Volcanic Aegis", "Volcanic Grips", "Volcanic Treads" },
		{ "Fiery Helm", "Fiery Breastplate", "Fiery Gauntlets", "Fiery Greaves" },
		{ "Hellplate Casque", "Hellplate Cuirass", "Hellplate Bracers", "Hellplate Greaves" },
		{ "Boreal Epiphany", "Boreal Resolve", "Boreal Might", "Boreal March" },
		{ "Brow of Ice", "Core of Ice", "Arms of Ice", "Feet of Ice" },
		{ "Skraevwing Helmet", "Skraevwing Jacket", "Skraevwing Gloves", "Skraevwing Boots" },
		{ "Draskscale Helmet", "Draskscale Plate", "Draskscale Gauntlets", "Draskscale Greaves" },
		{ "Shocking Gaze", "Shocking Heart", "Shocking Grasp", "Shocking Stride" },
		{ "Lightning Helm", "Lightning Plate", "Lightning Gloves", "Lightning Boots" },
		{ "Eye of the Swarm", "Shell of the Swarm", "Clutches of the Swarm", "Dance of the Swarm" },
		{ "Visage of Thorns", "Mantle of Thorns", "Grasp of Thorns", "Stride of Thorns" },
		{ "Sight of Stone", "Heart of Stone", "Might of Stone", "Pillars of Stone" },
		{ "Gnasher Cap", "Gnasher Cloak", "Gnasher Grips", "Gnasher Treads" },
		{ "Quillspike Mask", "Quillspike Jacket", "Quillspike Grips", "Quillspike Boots" },
		{ "Shrikedown Helm", "Shrikedown Plate", "Shrikedown Gloves", "Shrikedown Greaves" },
		{ "Dark Watch", "Dark Marrow", "Dark Embrace", "Dark Path" },
		{ "Visage of the Rift", "Mantle of the Rift", "Embrace of the Rift", "Striders of the Rift" },
		{ "Light's Crown", "Light's Virtue", "Light's Refuge", "Light's Walk" },
		{ "Crest of Valour", "Aegis of Valour", "Gauntlets of Valor", "Greaves of Valor" },
		{ "The Skullforge", "error", "error", "error" },
		{ "Tragic Echo", "error", "error", "error" },
		{ "Prismatic Grace", "error", "error", "error" }};
	int ArmorPerk[][4]{
		{ 0, 0, 0, 0 },
		{ 3, 20, 25, 25 },
		{ 33, 33, 3, 16 },
		{ 26, 35, 35, 4 },
		{ 14, 25, 25, 6 },
		{ 22, 4, 22, 12 },
		{ 17, 29, 12, 29 },
		{ 41, 41, 27, 17 },
		{ 46, 46, 41, 7 },
		{ 44, 44, 7, 42 },
		{ 9, 31, 14, 14 },
		{ 13, 36, 33, 36 },
		{ 11, 5, 4, 5 },
		{ 2, 11, 26, 11 },
		{ 37, 37, 30, 9 },
		{ 16, 16, 38, 2 },
		{ 25, 25, 46, 8 },
		{ 41, 43, 16, 43 },
		{ 43, 32, 43, 13 },
		{ 45, 8, 45, 20 },
		{ 0, 1000, 1000, 1000 },
		{ 0, 1000, 1000, 1000 },
		{ 0, 1000, 1000, 1000 }};
	int ArmorCellSlot[][4]{
		{ 0, 0, 0, 0 },
		{ 1, 5, 5, 3 },
		{ 2, 2, 4, 1 },
		{ 4, 4, 3, 3 },
		{ 5, 1, 3, 4 },
		{ 3, 3, 1, 1 },
		{ 2, 2, 2, 5 },
		{ 3, 3, 5, 5 },
		{ 5, 1, 5, 1 },
		{ 4, 2, 2, 2 },
		{ 2, 4, 2, 3 },
		{ 4, 5, 3, 5 },
		{ 1, 1, 1, 1 },
		{ 1, 1, 3, 3 },
		{ 1, 4, 4, 4 },
		{ 4, 2, 2, 2 },
		{ 3, 3, 5, 5 },
		{ 5, 5, 2, 2 },
		{ 4, 5, 4, 2 },
		{ 3, 3, 1, 5 },
		{ 1, 1000, 1000, 1000 },
		{ 3, 1000, 1000, 1000 },
		{ 4, 1000, 1000, 1000 }};
